//! Integration tests for the note document model.
//!
//! Exercises the full module against the `nb 7.24.0` corpus,
//! including real `include_bytes!` fixtures generated by pinned
//! `nb 7.24.0`, property-based round-trip tests for every
//! kind, and the index-invariants over the ownership partition
//! for every W1 + E1-E11 Resolution Table case.

#![allow(dead_code)] // strategy helpers shared across proptest modules

mod common;
mod format_dispatch;
mod heading_rules;
mod include_bytes_round_trip;
mod partition_regressions;
mod proptest;
mod resolution_table;

/// Pinned `nb 7.24.0` writer output for a titled tagged Note.
/// Generated by `tests/integration/probe_dump.rs` against
/// `nb 7.24.0` and committed as a fixture. This is the EXACT
/// byte content `nb 7.24.0` writes for an `add_note` with
/// title and tags, captured by reading the file back from
/// disk after the writer completes.
///
/// The fixture's trailing blank line at EOF is intentional
/// writer output (a final `\n\n` after the body), not a
/// formatting defect. The `.gitattributes` at the repository
/// root disables the blank-at-eol whitespace check for the
/// `tests/integration/fixtures/*.md` path.
pub(crate) const NOTE_FIXTURE: &[u8] = include_bytes!("../fixtures/note-fixture.md");

/// Pinned `nb 7.24.0` writer output for a Todo with checkbox
/// and terminal Tags. Same trailing-blank-line exception as
/// `NOTE_FIXTURE` (see `.gitattributes`).
pub(crate) const TODO_FIXTURE: &[u8] = include_bytes!("../fixtures/todo-fixture.md");

/// Pinned `nb 7.24.0` writer output for a tagged offline
/// Bookmark. Same trailing-blank-line exception as
/// `NOTE_FIXTURE` (see `.gitattributes`).
pub(crate) const BOOKMARK_FIXTURE: &[u8] = include_bytes!("../fixtures/bookmark-fixture.md");
